// Generated by scripts/sync-shared.mjs from shared/client/settings/plugin-card-seat.ts. Do not edit this copy; edit the shared source and run "node scripts/sync-shared.mjs".
/**
 * Family plugin-card seat (issue #1589).
 *
 * A family plugin contributes its settings card to whichever plugin-card seat
 * the running host actually declares:
 *
 * - `web-ui.plugin.item` — the list seat declared by the dsh-web-settings
 *   group section (this family's own first-level "Web UI plugins" section);
 * - `settings.plugin.item` — the official keyed seat of the harness's
 *   `ui-settings-plugins` tab, keyed by the settings namespace the card edits.
 *
 * The seat is a property of the deployment, not of the plugin: a profile that
 * installs a family plugin without dsh-web-settings declares only the official
 * seat, and one that carries the group declares only the family seat. Probing
 * and falling back keeps the card reachable in both, and turns a silent
 * no-card outcome (a swallowed registration error) into one logged warning.
 *
 * Both seats carry the same empty owner share and a locale namespace of the
 * registrant's choosing, so one component serves either dispatch.
 *
 * The shared tree has no client-SDK dependency, so this module reads its
 * context through the structural shape below; callers pass the plugin's own
 * `ctx`.
 */

/** The slot-registry members this helper uses (structurally satisfied by ctx.slots). */
export interface PluginCardSlots {
  /** Declared-spec probe; absent on an older service surface. */
  spec?(key: string): unknown
  /** Declaration-lifetime callback installer. */
  inject(key: string, callback: () => unknown): unknown
  /** Contribution of one card entry. */
  register(options: never, component: never): unknown
}

/** The slice of the client context a card contribution needs. */
export interface PluginCardContext {
  slots: PluginCardSlots
}

/** Owner share of a plugin card (both seats supply nothing). */
export interface SettingsPluginItemOwnerProps {
  /** Marker field: card owner props are intentionally empty. */
  children?: never
}

/** One family plugin's card contribution. */
export interface PluginCardSeat {
  /** Settings namespace the card edits (the official seat's dispatch key). */
  namespace: string
  /** Family list-seat entry id. */
  id: string
  /** Family list-seat sort order. */
  order?: number
  /** Family list-seat display label; the official keyed seat carries none. */
  label?: () => string
  /** Locale namespace the card renders with. */
  locale: string
  /** Business-face factory of the registration. */
  inject?: () => object
  /**
   * The card component. Its props type is the seat's composed shape, which is
   * chosen at runtime, so the helper takes it erased; the registrant keeps its
   * own precise typing at the call site.
   */
  component: unknown
}

/** Whether the running host declares the official keyed plugin-card seat. */
export function officialPluginCardSeatDeclared(ctx: PluginCardContext): boolean {
  const spec = ctx.slots.spec
  if (typeof spec !== 'function') return false
  try {
    return spec.call(ctx.slots, 'settings.plugin.item') !== undefined
  } catch {
    // An older service surface that cannot answer: treat the seat as absent.
    return false
  }
}

/** Report a refused registration instead of leaving the user with no card. */
function warnRefusedSeat(seat: string, error: unknown): void {
  try {
    console.warn(`[dsh-web] plugin card registration into "${seat}" was refused; the card will not render`, error)
  } catch {
    // Best-effort console write; a failed warning must not break the plugin.
  }
}

/**
 * Contribute one family plugin card to the seat this host declares.
 * @param ctx - client context (its slot registry decides the seat).
 * @param seat - the card contribution.
 */
export function installPluginCard(ctx: PluginCardContext, seat: PluginCardSeat): void {
  const slots = ctx.slots
  const component = seat.component as never
  if (officialPluginCardSeatDeclared(ctx)) {
    const inject = seat.inject as never
    slots.inject('settings.plugin.item', () => {
      try {
        return slots.register({
          name: 'settings.plugin.item',
          key: seat.namespace,
          locale: seat.locale,
          ...(seat.inject === undefined ? {} : { inject }),
        } as never, component)
      } catch (error) {
        warnRefusedSeat('settings.plugin.item', error)
        return () => {}
      }
    })
    return
  }
  const inject = seat.inject as never
  slots.inject('web-ui.plugin.item', () => {
    try {
      return slots.register({
        name: 'web-ui.plugin.item',
        id: seat.id,
        ...(seat.order === undefined ? {} : { order: seat.order }),
        ...(seat.label === undefined ? {} : { label: seat.label }),
        locale: seat.locale,
        ...(seat.inject === undefined ? {} : { inject }),
      } as never, component)
    } catch (error) {
      warnRefusedSeat('web-ui.plugin.item', error)
      return () => {}
    }
  })
}
